### ISSUE TITLE
hydra.errors.InstantiationException: Error locating target 'src.training.diffuser.Diffuser', set env var HYDRA_FULL_ERROR=1 to see chained exception.

### ISSUE THREAD

**Issue by Vinayak-VG** [robincourant/DIRECTOR#2]
INFO: Using 16bit Automatic Mixed Precision (AMP)
[2024-07-24 19:29:57,635][lightning.pytorch.utilities.rank_zero][INFO] - Using 16bit Automatic Mixed Precision (AMP)
INFO: GPU available: True (cuda), used: True
[2024-07-24 19:29:57,668][lightning.pytorch.utilities.rank_zero][INFO] - GPU available: True (cuda), used: True
INFO: TPU available: False, using: 0 TPU cores
[2024-07-24 19:29:57,687][lightning.pytorch.utilities.rank_zero][INFO] - TPU available: False, using: 0 TPU cores
INFO: HPU available: False, using: 0 HPUs
[2024-07-24 19:29:57,687][lightning.pytorch.utilities.rank_zero][INFO] - HPU available: False, using: 0 HPUs
Error executing job with overrides: ['compnode.num_gpus=1', 'diffuser/network/module=C', 'dataset.trajectory.set_name=pure', 'checkpoint_path=/home/vinayak/NITAI/DIRECTOR/checkpoints', 'diffuser/network/module=ca_director', 'diffuser.guidance_weight=8.0']
Traceback (most recent call last):
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'src.training' has no attribute 'diffuser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/vinayak/NITAI/DIRECTOR/src/training/diffuser.py", line 20, in <module>
    from src.metrics.callback import MetricCallback
  File "/home/vinayak/NITAI/DIRECTOR/src/metrics/callback.py", line 5, in <module>
    from src.metrics.modules.caption import CaptionMetrics
  File "/home/vinayak/NITAI/DIRECTOR/src/metrics/modules/caption.py", line 9, in <module>
    from torchmetrics.utilities import dim_zero_cat
ImportError: cannot import name 'dim_zero_cat' from 'torchmetrics.utilities' (/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/torchmetrics/utilities/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/_internal/utils.py", line 658, in _locate
    raise ImportError(
ImportError: Error loading 'src.training.diffuser.Diffuser':
ImportError("cannot import name 'dim_zero_cat' from 'torchmetrics.utilities' (/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/torchmetrics/utilities/__init__.py)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vinayak/NITAI/DIRECTOR/src/evaluate.py", line 83, in <module>
    main()
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/vinayak/NITAI/DIRECTOR/src/evaluate.py", line 26, in main
    diffuser = instantiate(config.diffuser)
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.training.diffuser.Diffuser', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: diffuser

I am getting the above error when I run - HYDRA_FULL_ERROR=1 python3 src/evaluate.py compnode.num_gpus=1 diffuser/network/module=C dataset.trajectory.set_name=pure checkpoint_path=/home/vinayak/NITAI/DIRECTOR/checkpoints diffuser/network/module=ca_director diffuser.guidance_weight=8.0

What should be done in this case?

**Comment by robincourant** [comment]
Hi,

It might be related to your `PYTHONPATH`. Could you try running `export PYTHONPATH=$(pwd)` before launching the script?

**Comment by Vinayak-VG** [comment]
Yes, I tried that before but of no use. I am not able to understand what exactly needs to be done. From where exactly is hydra trying to locate the target?

**Comment by robincourant** [comment]
You're supposed to launch the script from the root of this repository.

**Comment by Vinayak-VG** [comment]
Yeah I did run that command - "HYDRA_FULL_ERROR=1 python3 src/evaluate.py ....." in the **DIRECTOR** directory but still I get this error. Is this because of VS Code?

**Comment by robincourant** [comment]
Maybe your `PYTHONPATH` in VS Code is not set properly?

**Comment by robincourant** [comment]
After re-reading your error message, it seems that it comes from you `torchmetrics` module:
```
ImportError: cannot import name 'dim_zero_cat' from 'torchmetrics.utilities' (/home/vinayak/miniconda3/envs/st2v/lib/python3.10/site-packages/torchmetrics/utilities/init.py)
```

I use `torchmetrics==1.4.0.post0`

**Comment by maoning123ab** [comment]
I've encountered the same issue as well, however, the suggested solutions above did not seem to work in my case.

**Comment by robincourant** [comment]
Hi, 
Could you copy paste the error message please?

**Comment by maoning123ab** [comment]
Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Error executing job with overrides: ['diffuser/network/module=incontext_director', 'dataset.trajectory.set_name=mixed']
Traceback (most recent call last):
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
AttributeError: module 'src.training' has no attribute 'diffuser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
  File "/home/e723/anaconda3/envs/director/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/e723/mn/DIRECTOR/src/training/diffuser.py", line 9
    fromport PlotCollectionm evo.tools.plot i
             ^^^^^^^^^^^^^^^
SyntaxError: invalid syntax

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/_internal/utils.py", line 658, in _locate
    raise ImportError(
ImportError: Error loading 'src.training.diffuser.Diffuser':
SyntaxError('invalid syntax', ('/home/e723/mn/DIRECTOR/src/training/diffuser.py', 9, 10, 'fromport PlotCollectionm evo.tools.plot i\n', 9, 25))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/e723/mn/DIRECTOR/src/train.py", line 70, in <module>
    main()
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/e723/mn/DIRECTOR/src/train.py", line 52, in main
    diffuser = instantiate(config.diffuser)
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
  File "/home/e723/anaconda3/envs/director/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'src.training.diffuser.Diffuser', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: diffuser

**Comment by robincourant** [comment]
You seem to have a error of syntax:
'SyntaxError('invalid syntax', ('/home/e723/mn/DIRECTOR/src/training/diffuser.py', 9, 10, 'fromport PlotCollectionm evo.tools.plot i\n', 9, 25))'

**Comment by maoning123ab** [comment]
i"I see it now, thank you. I was too careless."
